### ISSUE TITLE
Not working on IRCTC after home page

### ISSUE THREAD

**Issue by nitin2953** [Dhruv-Techapps/acf-docs#209]
**Describe the bug**
I have successfully created a configuration to search train from IRCTC home page

**To Reproduce**
1. Import this configuration [Search trains config.zip](https://github.com/Dhruv-Techapps/auto-click-auto-fill/files/7717468/Search.trains.zip)
2. Go to '[https://www.irctc.co.in/nget/train-search](https://www.irctc.co.in/nget/train-search)'
3. After it search for trains, I can't do any anything, I think the url change without DOM load event
4. Even another config with train list url don"t work

**Expected behavior**
It should work regardless of any user intraction, weaather the DOM is fully loaded or not (when triggered with hotkeys)

**Screenshots**

**Desktop:**
 - OS: Windows 10 2004
 - Chrome
 - Version 96.0.4664.110

**Comment by betagoyal** [comment]
it works on home page

**Comment by dharmesh-hemaram** [comment]
https://youtu.be/IbfcO4ndgIw
