### ISSUE TITLE
GOTO option request in addon 

### ISSUE THREAD

**Issue by betagoyal** [Dhruv-Techapps/acf-docs#294]
want to request a feature in Addon.
There should be one more action . Where if condition does not match then it goes to one of above element finder on configuration page .

**Comment by betagoyal** [comment]
![Image](https://user-images.githubusercontent.com/16471212/227698658-d175a6d5-d5b8-41f0-98db-6e70400a6b9d.png)

**Comment by betagoyal** [comment]
new development is stopped ?

**Comment by betagoyal** [comment]
go to feature is in action and it should be in add on function

**Comment by dharmesh-hemaram** [comment]
available in DEV version
