### ISSUE TITLE
Suggestion batch macro and macro configaration start 

### ISSUE THREAD

**Issue by Emoncht** [Dhruv-Techapps/acf-docs#330]
I have a different Idea about batch/Group. 

Can we add Configaration into a group? Now we can add new config with a url, But I am suggestion that we will add new config Inside a group. in this way we can add multiple macro in a single url.(I Know I can do this without group) but if we group all these macro we can create a flow.

Also we can run the group macro with webhook url/When button click in html with button ID/ we can can also Run the group with api. There are many use cases. 

In my case, Suppose I want to complete an order for PUBG 60 UC, i need to manually click on the 60 UC when the midasbuy.com loads. If AUTO CLICKER-AUTOFILL extension had group system I could have load the GROUP and sit back.

insort I am suggesting that

-  Add group system
- Add system that group can be loaded by button-id. (Whenever a html button clicked it will load the group config)
- Add group/config load when a webhook url triggered.

Since there is only one auto system which is "(default) once browser is refresh or new page is loaded extension auto loads with it." I am suggesting to add more.
```[tasklist]
### Tasks
```

**Comment by dharmesh-hemaram** [comment]
I have some doubts on this. like once a configuration is completed and mmoved to next configruation how it know like page is ready for operation or does it has loaded the right web page without any error. 

We we match configuration with url they all are connected and work in group only based on pages it next loads.

Let me know if this dont work for you.

Like create configuration and use the url for mapping and just initiate the flow and it will do all process of it.

e.g. we have combination of configuratio to purchage ticket from our ticketing system. 

it consist of ticket selecting , then booking confirmation , to payment

**Comment by Emoncht** [comment]
**once a configuration is completed and mmoved to next configruation how it know like page is ready for operation or does it has loaded the right web page without any error.**

Since we are clicking elements by xpath if error happens there shouldn’t be that pirticular Xpath. Right?

I was using your extension for a long time. Now i need to completely automate my task. And using nodriver for the same task. Just having captcha problems sometime. If captcha shows I was closing browser and connect it to a proxy then opening the same task again.
