### ISSUE TITLE
Reload the URL if the extension context gets invalidated when the extension is updated

### ISSUE THREAD

**Issue by kazuna** [Dhruv-Techapps/acf-docs#333]
As reported at the Discord channel.
https://discord.com/channels/702091948902711388/1210636238458069022

Chrome can update the extension automatically and when it happens the extension context will get invalidated and the actions will stop executing. The new status bar will indicate this saying "[X] Extension context invalidated." in this situation.

One idea for this problem would be the extension to reload the URL when the extension context gets invalidated.

**Comment by kazuna** [comment]
The extension just got updated to v3.5.2 and the extension running just stopped working and says "[X] Extension context invalidated." in the status bar.

Instead of just showing the invalidated message, I would like the extension to reload the URL to keep the extension running.

**Comment by dharmesh-hemaram** [comment]
Its under DEV deploment
