### ISSUE TITLE
OCR feature request 

### ISSUE THREAD

**Issue by betagoyal** [Dhruv-Techapps/acf-docs#340]
I request a feature there we can use OCR feature of any available image on that page with help of open source project like
https://github.com/tesseract-ocr/tesseract

**Comment by dharmesh-hemaram** [comment]
Its available in [DEV](https://dev.getautoclicker.com) env .

to use same 
**ElementFinder** - `target input field in which captcha answer will be updated.`
**Value** - `Image::xpath of the image from which captcha need to be read`

This feature is available for **PRO** users only.
