### ISSUE TITLE
Post Batch Repeat Action

### ISSUE THREAD

**Issue by tango125** [Dhruv-Techapps/acf-docs#376]
Would it be possible, for there to be an "end action" to a batch?  Currently it's a choice between batch and repeat.

With my suggestion, repeat should be an option after all the batch too, but maybe it could also be going to a different URL?

**Comment by tango125** [comment]
Or even a "playlist" of config, so it can go from one to the next.

**Comment by dharmesh-hemaram** [comment]
Can you give some examples

**Comment by tango125** [comment]
I hope my example make sense, it's not real.

Say there is a 50 times click limit to the website I'm using this on and refreshing the browser would reset the count.  With the program right now, I can just asking it to refresh at the end of sequence or after the 50 times run, it'd just stay at the screen and wait for me to refresh manually.

So I was hoping it could, say after doing the batch 50 times, it'd know to refresh.  So it'd start the 50 times again.

The playlist idea is sort of simlar, but so it'd run from 1 set of "settings" to the next, so I could have the initial batch of 50 for Setting 1, then it'd know to run Setting 2, which is refresh.

**Comment by dharmesh-hemaram** [comment]
@tango125 ,

Sorry for replying late but I'm back with solution for you

Step 1:
Set the batchRepeat value to your html tag 
![image](https://github.com/Dhruv-Techapps/acf-docs/assets/2290202/cf273c2f-0dd5-45f1-a2c2-92574908f40d)
![image](https://github.com/Dhruv-Techapps/acf-docs/assets/2290202/0e25d418-393e-4149-8150-771f88a8a49d)
it can be done with 
- elementFinder - `//html`
- value - `Attr::set::session::<batchRepeat>`

Step 2 : Refresh
add another action 
- elementFinder - `//html`
- value - `LocationCommand::reload`
Add Addon on it
![image](https://github.com/Dhruv-Techapps/acf-docs/assets/2290202/d67a99fe-5d18-49ed-89c8-707cfee06115)

- elementFinder - `//html`
- Condition - `=`
- Value - `50`
- Value Extractor - `@session`

Rechec-options - `Skip`
[btach refresh.json](https://github.com/Dhruv-Techapps/acf-docs/files/15283196/btach.refresh.json)
