### ISSUE TITLE
Discussion not available?

### ISSUE THREAD

**Issue by djkeh** [Dhruv-Techapps/acf-docs#394]
Hi, I don't see a button to write things in the discussions, could anyone please explain what happened?
I came here to ask a question about using auto clicker, is it not operating any more?

**Comment by AJolly** [comment]
@djkeh discussions look fine to me? https://github.com/Dhruv-Techapps/acf-docs/discussions

**Comment by djkeh** [comment]
@AJolly I dunno man, I don't see any button to write a question in the browser. I found the `+` button at the github mobile though.

**Comment by dharmesh-hemaram** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3fc615b8-b493-407e-a387-e5a408486b0f">

You need to login into Github to have new discussion created

**Comment by djkeh** [comment]
Yeah, that button at the top right corner. I still don't have it.

**Comment by dharmesh-hemaram** [comment]
We have checked the organisations interaction limit also . It’s all disabled . We will check further with GitHub and update you . Thank you for raising this issue 

![IMG_2773](https://github.com/user-attachments/assets/a0de0fe1-5e1c-444e-978c-3f4ee0f97d7a)

**Comment by djkeh** [comment]
Hello, any updates on this? The button is still not visible.

**Comment by dharmesh-hemaram** [comment]
Hi @djkeh ,

We had a connect with Github Support team and made some changes at organisation level can you please check now.?

**Comment by djkeh** [comment]
<img width="973" alt="image" src="https://github.com/user-attachments/assets/b88ed42c-472f-46b2-8da3-129a2aa78c97">

Yup, finally it's working. Big thanks!
