### ISSUE TITLE
Google backup not available for beta:

### ISSUE THREAD

**Issue by AJolly** [Dhruv-Techapps/acf-docs#395]
**Access blocked: Auto Clicker - AutoFill [Beta] has not completed the Google verification process

Auto Clicker - AutoFill [Beta] has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/).
If you are a developer of Auto Clicker - AutoFill [Beta], see [error details](https://accounts.google.com/).
Error 403: access_denied**

**Comment by dharmesh-hemaram** [comment]
> **Access blocked: Auto Clicker - AutoFill [Beta] has not completed the Google verification process
> 
> 
> 
> 
> 
> Auto Clicker - AutoFill [Beta] has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/).
> 
> If you are a developer of Auto Clicker - AutoFill [Beta], see [error details](https://accounts.google.com/).
> 
> Error 403: access_denied**
> 
> 

Please use stable version

**Comment by AJolly** [comment]
Yep, stable works fine, just figured i'd report the issue for the beta.
