### ISSUE TITLE
How can i check if the textfield is emty or not ?

### ISSUE THREAD

**Issue by MaiLinhUwU** [Dhruv-Techapps/acf-docs#398]
i want to check if the textfield has text in it if it does then go to the next one, if is not then stop and wait for another few sec

**Comment by dharmesh-hemaram** [comment]
You can use addon here .

Element finder target to input field

Condition equals

Under value you can use regular expression like \d{6} this will wait to enter 6 digits in input field you can set retry to keep trying until the condition matches
