### ISSUE TITLE
Delay click a button in number of seconds

### ISSUE THREAD

**Issue by nguyenhung1121990** [Dhruv-Techapps/acf-docs#400]
Hi there, I am using your tool and would need your help to advise how can I set delay click a button in number of seconds in a web-form, for example after 5s, the Submit button will be clicked, just enough!

Thanks in advance.

**Comment by dharmesh-hemaram** [comment]
Checkout unit wait for action https://getautoclicker.com/docs/4.x/action/init-wait/
