### ISSUE TITLE
Action doesn't work on mobile but mobile (no touch) is available

### ISSUE THREAD

**Issue by hochonman0425** [Dhruv-Techapps/acf-docs#401]
I'm try to setting some click action in shopping website on mobile, I use PC with chrome browser to testing,
when I open the DEVtools to find the Xpath and create a action, then refresh the website to test the action,
the status bar show action is "Done" but the field which I need to click was no changed,
![03](https://github.com/user-attachments/assets/e244a796-5a44-4c3b-8f0e-3f6817466a4f)
but I switch the device type to mobile (no touch), the click action was working, what is the different of these two mode?
![01](https://github.com/user-attachments/assets/ee3c5f36-76aa-4f0d-94bf-5e2eb827e62d)
![02](https://github.com/user-attachments/assets/6a0729f4-986c-4105-9fb8-7c5f01014188)

**Comment by dharmesh-hemaram** [comment]
Can you share the URL of website to test

**Comment by dharmesh-hemaram** [comment]
Closing this comment as no response
