### ISSUE TITLE
How to open a link which is not a hyperlink but is in a text form.

### ISSUE THREAD

**Issue by BlackGrimReaper** [Dhruv-Techapps/acf-docs#402]
I have a website that displays a link in text form, and it's not clickable or a hyperlink. It uses code like this:

```html
<span style="color: rgb(156, 156, 156); --darkreader-inline-color: #bbb3a5;" data-darkreader-inline-color="">https://www.xyz.com/product-123</span>
```

I want to convert this element to a clickable hyperlink, and I also want it to open in a new tab automatically. How can I do that?

**Comment by dharmesh-hemaram** [comment]
Will check on this . It's not issue please connect over discord to further questions

**Comment by dharmesh-hemaram** [comment]
Extension don't have such features to convert text into link.
