### ISSUE TITLE
No way do insert line break as value

### ISSUE THREAD

**Issue by csatalos** [Dhruv-Techapps/acf-docs#403]
I was trying from Chrome PC ver 115.0.5790.102.

Sorry if it was my mistake that I couldnt figure it out.

**Comment by dharmesh-hemaram** [comment]
We are working on it . Changes are currently in Dev version . We will
release same after testing on stable version .

Regards,
Dharmesh Hemaram

**Comment by dharmesh-hemaram** [comment]
Available on stable version

**Comment by csatalos** [comment]
Thank you, but could you tell me how to insert line break? I've tried even with the dev version and looked for it at the documentation but with no success

**Comment by dharmesh-hemaram** [comment]
Click on the `I` button left to the value button to convert it into text
area . And then you can add text with new line just by using enter key

Regards,
Dharmesh Hemaram

**Comment by dharmesh-hemaram** [comment]
![image](https://github.com/user-attachments/assets/b087766a-d9c9-442b-82a8-7e726d3b2375)
