### ISSUE TITLE
Make "Tabs::update" command to work with MV3 version

### ISSUE THREAD

**Issue by kazuna** [Dhruv-Techapps/acf-docs#417]
Discussed on this Discord thread.
https://discord.com/channels/702091948902711388/1258173603380334611

Dharmesh — Today at 4:25 AM
We need to find another solution

When first tabs::update goes to service worker if its inactive it becomes active .
and if we pass another tabs::update request with a delay of 1 sec that will work correctly as on that time service worker will be active .
I need to rethink over this solution something like scheduler which can trigger in interval

**Comment by dharmesh-hemaram** [comment]
We added some improvement on service worker side to keep alive when sending message . 

Please check and close ticket if working
