### ISSUE TITLE
Remove an HTML element if present

### ISSUE THREAD

**Issue by Vigneshgvs** [Dhruv-Techapps/acf-docs#418]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when LinkedIn shows the "Applied" jobs again in the job searches.

**Describe the solution you'd like**
Instead of clicking 'x' if the job is "Applied" (which will alter LinkedIn's algorithm, so avoiding it) - which can be done by your extension, removing (or by hiding) the parent HTML element itself (if it has 'Applied in it') from the page will give us only the list of unapplied jobs.

**Describe alternatives you've considered**
Mentioned above.

**Additional context**
[Image for LinkedIn showing "Applied" jobs in the searches](https://imgur.com/a/E3UvFb8)

**Comment by dharmesh-hemaram** [comment]
Deployed on DEV environment.

**Comment by Vigneshgvs** [comment]
Thanks was able to use: //div[@data-view-name="job-card"][.//li[text()="Applied"]] and FormEvents::remove
Is this the fix you gave or something else?

**Comment by dharmesh-hemaram** [comment]
It's the same.
