### ISSUE TITLE
I cant use my already created file 

### ISSUE THREAD

**Issue by ayubbaoch** [Dhruv-Techapps/acf-docs#421]
I have created a configuration file of 252 rows to fill out my gig package a long time ago.

I was using it without any issues. today when I faced the error the element not found error. i even pasted the exact URL of the page.

please let me know how I can solve it

I even deleted it and imported it but no

**Comment by dharmesh-hemaram** [comment]
Resolved on [discord](https://discord.gg/ubMBeX3)
