### ISSUE TITLE
Cannot Configure this form

### ISSUE THREAD

**Issue by mz26678** [Dhruv-Techapps/acf-docs#422]
Hi there, why can't i configure this form ?

http://minutemaid2024.jcmsonline.com/

after a few tries, I got the message UNDEFINED in the configuration page. 

Pls Help. Thanks

**Comment by dharmesh-hemaram** [comment]
Check this out. It had page within iframe

[Draft_ Minute Maid _ Coca-Cola Contest.json](https://github.com/user-attachments/files/16917229/Draft_.Minute.Maid._.Coca-Cola.Contest.json)

**Comment by mz26678** [comment]
Thanks a lot Dharmesh.

btw, I've been trying to set the checkbox (TERMS & CONDITIONS) but failed
after many attempt. Appreciate if you could help with this one also:

ELEMENT FINDER
***@***.***="userInput"]/div/div/div/div[2]/div/div/div[3]

VALUE
MouseEvents::click

**Comment by mz26678** [comment]
Hi there,

First and foremost thanks again for the draft that you gave earlier.

I understand that you cannot automate file upload right?

What if I want the T&C checkbox to be auto-checked and the form will be
automatically submitted right after I upload a file? Is that possible?

https://form.jotform.com/241604791765463
