### ISSUE TITLE
Make Clipboard::Paste:: more usefull

### ISSUE THREAD

**Issue by Mluna97** [Dhruv-Techapps/acf-docs#425]
**Is your feature request related to a problem? No, but** 
The case is that I need to persist one var through pages navigation. The way I got to do this was to copy the value to clipboard, and that works great, but now, I need to use that value as a position of a slice.  Ex: 
"blue,red,white".split(",")[Clipboard::Paste]; is what I imagined but it doesn't work

## Solution I think
I think it might be usefull to allow the usage of Clipboard::Paste or Query param in Func::. 

## Alternative solution
Also, I think it would be great to put global vars, not js ones.

**Comment by dharmesh-hemaram** [comment]
The feature is available in the [DEV](https://dev.getautoclicker.com/) environment, version `4.0.39.4`. Please refer to the documentation for instructions on how to use it https://getautoclicker.com/docs/4.x/action-value/function/
