### ISSUE TITLE
Element Finder finds the last element from similar elements on the page (search from the bottom of the page)

### ISSUE THREAD

**Issue by AVAV19** [Dhruv-Techapps/acf-docs#427]
**Describe the bug**
Element Finder finds the last element from several similar elements on the page (basically, it starts search from the bottom of the page). 
All kinds of "getElementBy" were tried.

**Expected behavior**
The first elements from the similar elements shall be found starting from the top of the page

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser chrome
 - Version 128.0.6613.138

**Comment by dharmesh-hemaram** [comment]
Hi @AVAV19 ,

Can you please help me with selector you are using .

**Comment by AVAV19** [comment]
Hi, In this case it is ClassName::td-list-column-langs-link
Andrei

**Comment by AVAV19** [comment]
Basically, there are 7 class elements td-list-column-langs-link, but the extension selects and clicks only on the last element though it is supposed to select the first element.

**Comment by dharmesh-hemaram** [comment]
We just tested the className selector on our test page and it clicks all the elements which matches that class name and not last one.

<img width="1843" alt="Screenshot 2024-09-19 at 5 34 59 PM" src="https://github.com/user-attachments/assets/4fceaaeb-fdc0-446e-a8b5-519be25483d4">

```js 
document.querySelectorAll("button").forEach((ele) => {
    ele.addEventListener("click",(e) => console.log(e.target))
});
```

<img width="878" alt="image" src="https://github.com/user-attachments/assets/c3d80558-1418-48ad-b31b-9659855871dc">


---

> Would recommend to change the selector to more narrow down the button on which you like to click.

**Comment by dharmesh-hemaram** [comment]
regex in url or element finder?

**Comment by AVAV19** [comment]
If possible, both options (replace ?):
in url https://gengo.com/t/jobs/details/ ?
element finder: //a[@href="https://gengo.com/t/jobs/details/ ?  "]

**Comment by dharmesh-hemaram** [comment]
URL support partial match as well https://getautoclicker.com/docs/4.x/configuration/url/

xpath you can use contains check for partial check https://getautoclicker.com/docs/4.x/action/element-finder/

for further queries connect over discord https://discord.gg/ubMBeX3
