### ISSUE TITLE
How to create a local paramenter when a condition is succeful

### ISSUE THREAD

**Issue by rickyangtw** [Dhruv-Techapps/acf-docs#431]
Dear Sir
  I want to create a local paramenter when a condition is succeful.
  For example
  If find a input box and assign a string succeful, setup "count" parameter as count=count +1

if some command can do this?
Thanks

**Comment by dharmesh-hemaram** [comment]
Hi @rickyangtw ,

Can you please share also scenario why its required may be we have alternate solution for same.

**Comment by rickyangtw** [comment]
Dear @dharmesh-hemaram 
   Thank your help.
   My scenario like attach file that use "Practice Form"
[example.json](https://github.com/user-attachments/files/17096572/example.json)

  1. Use the attach configuration to setup fist input box value as "name1"
  
![image](https://github.com/user-attachments/assets/36668b5f-fcd1-4036-baa3-c148c90a2b94)


  2. After first input box value set to "name1"
      - I want to create a **temp parameter name** "count" as value 0
      - And make count=count+1, so the count value is 1
      
  3. if we setup 2nd input box to name2 like below:
  
![image](https://github.com/user-attachments/assets/70b92510-189d-47c8-8a34-b4f9ffdadbf2)

  4. Then run count=count+1 again, so the "count" value should be 2

**Comment by dharmesh-hemaram** [comment]
But if the input fields are in same form we can directly set the value as name1 and name2 


Are you aware of actionrepeat and batchrepeat and sessioncount

**Comment by rickyangtw** [comment]
Dear @dharmesh-hemaram 
  Thanks
  I just want to a way to setup a temp "count" parameter to count how many time I fill the input box succeful.
  For "actionrepeat and batchrepeat and sessioncount", I don't know it, but I can try, do you have any example?

Thanks

**Comment by dharmesh-hemaram** [comment]
[Batch repeat](https://getautoclicker.com/docs/4.x/action-value/batch-repeat/)

[Session count](https://getautoclicker.com/docs/4.x/session/overview/)

**Comment by dharmesh-hemaram** [comment]
@rickyangtw ,

is your issue resolved?

**Comment by rickyangtw** [comment]
it is ok, please close this issue
Thank your help.

**Comment by rickyangtw** [comment]
it is ok, please close this issue
Thank your help.
