### ISSUE TITLE
wizard.js:1 Uncaught TypeError: crypto.randomUUID is not a function.

### ISSUE THREAD

**Issue by mean-cj** [Dhruv-Techapps/acf-docs#432]
Hi @dharmesh-hemaram 

I'll explain with pictures instead.
Did you restrict access to the main Project? It seems like I used to help fix the code before.

chrome-extension://iapifmceeokikomajpccajhjpacjmibe/wizard.js

![image](https://github.com/user-attachments/assets/11075c74-10b8-4899-beed-5b30ea83feb0)

![image](https://github.com/user-attachments/assets/34a0ee0f-a1c1-46e7-ae92-9ae3b53e9a42)

![image](https://github.com/user-attachments/assets/7821f564-9333-42b1-b84c-02c904e73c0a)

![image](https://github.com/user-attachments/assets/c62ff3ec-ef5f-4dbb-a79d-20a1d2a2383e)

Thanks

**Comment by dharmesh-hemaram** [comment]
Thanks for detailed issue . Will look into it

**Comment by dharmesh-hemaram** [comment]
Note that window.crypto.randomUUID is only available under HTTPS context: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

Are you using on website which is still running on http?.

You can also try Recorder from dev-tools and export configuration from it. 

https://developer.chrome.com/docs/devtools/recorder

**Comment by dharmesh-hemaram** [comment]
fixed and deployed on DEV
