### ISSUE TITLE
URL matching depending on query params

### ISSUE THREAD

**Issue by indeed-a-genius** [Dhruv-Techapps/acf-docs#434]
I'd like have one config for https://test.getautoclicker.com/?ab=123 and another for https://test.getautoclicker.com/?ab=567

**Comment by dharmesh-hemaram** [comment]
You can use the complete url and create two configuration

**Comment by indeed-a-genius** [comment]
Thanks, exact works. 
But it can't be done with regex? For example `https://test.getautoclicker.com/?ab=12.*`

**Comment by dharmesh-hemaram** [comment]
But you need two configuration or else our url matches with regular
expression and partial match also checkout docs of same

Regards,
Dharmesh Hemaram

**Comment by indeed-a-genius** [comment]
Yes, I want to create two configs.
One that matches: https://test.getautoclicker.com/?ab=12* (so for example https://test.getautoclicker.com/?ab=12&o=i&n=m)
Second one that matches: https://test.getautoclicker.com/?ab=34* (so for example https://test.getautoclicker.com/?ab=34&c=x&g=p)
Is it possible?

**Comment by dharmesh-hemaram** [comment]
https://test.getautoclicker.com/?ab=12&o=i&n=m
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/b7d751f7-5c81-43be-9dd9-dc8c13c21d52">

https://test.getautoclicker.com/?ab=34&c=x&g=p
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/8e98d008-b42d-4de2-be63-a67897281dc0">

**Comment by indeed-a-genius** [comment]
thanks, that works!
I assumed  using `.*` is required when using regex
