### ISSUE TITLE
entering text and 2 query params into a single field

### ISSUE THREAD

**Issue by indeed-a-genius** [Dhruv-Techapps/acf-docs#435]
Is entering multiple values supported?
For example:
Query::something some text here Query::another

Or using Append or Prepend together with Query?

**Comment by dharmesh-hemaram** [comment]
You can have two actions and perform append query on same.

**Comment by indeed-a-genius** [comment]
But what's the syntax of appending a query?
for https://test.getautoclicker.com/?aaa=bbb I tried Append::Query::aaa but instead of placing "bbb" it places "Query::aaa"

**Comment by dharmesh-hemaram** [comment]
Its a bug we will address this
