### ISSUE TITLE
if my 1st Configuration is unable, how it's go for next Configuration automatically ? 

### ISSUE THREAD

**Issue by khalashihabib1** [Dhruv-Techapps/acf-docs#438]
look if my 1st or 2nd or 3dr my Configuration is unable , how it's go for next Configuration automatically ?
Suppose I set a number of configurations. Some of these configurations are sometimes enabled or disabled. If Unableable then does not go to next configuration. That is, the configuration that is enabled is no longer working automatically. For example I want to set many configurations and among them the only configuration that will be available is the one that works.
How to do it?
<img width="522" alt="Screenshot 2024-10-13 at 9 52 34 AM" src="https://github.com/user-attachments/assets/267d1600-622f-48fa-838c-4cb92c9d310d">
<img width="522" alt="Screenshot 2024-10-13 at 9 52 34 AM" src="https://github.com/user-attachments/assets/d56cd9d1-a4c9-4365-8435-66c261810f4f">

**Comment by rickyangtw** [comment]
Hi
You can use "Action Settings"

![image](https://github.com/user-attachments/assets/d49591d4-2dbd-4c49-8f43-683ea63b5d2b)

Turn on "Skip Action"

![image](https://github.com/user-attachments/assets/e155b97d-3b53-4430-b738-1bc69de4f94c)

**Comment by khalashihabib1** [comment]
devolop something like which is work for auto click on Schedule Appointment targeted month and year match when it's match to website calendar
date match just on month and year 
after set targeted date it's need to a popup to save date .

**Comment by dharmesh-hemaram** [comment]
@khalashihabib1 i didn't got your query. This place is if there are any issue with extension for queries please connect over discord
