### ISSUE TITLE
If can change time out value if xpath not found

### ISSUE THREAD

**Issue by rickyangtw** [Dhruv-Techapps/acf-docs#439]
Dear sir
   I create two actions.
   And setup action 1  "Action Setings" to "Skip Action" if xpath can't be found, so it will goto next one (action 2)

![image](https://github.com/user-attachments/assets/b25bfb92-d724-4570-a0a4-c81a12d824d6)

![image](https://github.com/user-attachments/assets/7401aabf-f27d-45fa-b151-cbbc7a20344a)

   But Action 1 need about 3 seconds to check xpath is not found then go to next item, it will make all process is slow
   Can we change the time out value?

Thanks

**Comment by dharmesh-hemaram** [comment]
Set retry and retry interval under action settings

Regards,
Dharmesh Hemaram

**Comment by dharmesh-hemaram** [comment]
Please connect over discord if still facing issue
