### ISSUE TITLE
Value is getting printed in form, Input is not taking from spreadsheet

### ISSUE THREAD

**Issue by surve325** [Dhruv-Techapps/acf-docs#440]
**Describe the bug**

When I am tring to fill any form it is printing Taking value (GoogleSheets::gg!A1)  <-- this is printing in output form.

please give me some solution.

**Comment by surve325** [comment]
printering spreadsheet name in form.
getting below error:
elementFinder: //input[@name="spreadsheetId"][@placeholder="Google Sheets ID"][@id="config-google-sheets-id"][@value=""]

**Comment by dharmesh-hemaram** [comment]
> **Describe the bug**
> 
> When I am tring to fill any form it is printing Taking value (GoogleSheets::gg!A1) <-- this is printing in output form.
> 
> please give me some solution.

```
We offer a generous daily allowance of 10 free Google Sheets API calls per user. This limit resets every day, providing you with a fresh set of 10 calls each day.

To unlock unlimited access to Google Sheets API calls, you have two options:

Subscribe to the Pro Version 
By upgrading to our Pro version, you gain unlimited access to Google Sheets API calls, allowing you to maximize productivity without worrying about daily limits.

Switch to a Public Profile 
Alternatively, you can switch your profile to public mode to enjoy unlimited access to Google Sheets API calls. This option is ideal for users who do not require private data handling and are comfortable sharing their configurations publicly.
```

https://getautoclicker.com/docs/4.x/action-value/google-sheets/
