### ISSUE TITLE
Batch autoclick/autofill will not finish

### ISSUE THREAD

**Issue by Hamkaascroissant** [Dhruv-Techapps/acf-docs#441]
For a page with a dropdownmenu I made a batch with a couple of selection actions followed by mouseclick actions, so it should select a certain option from the menu, click on the button on the webpage to confirm the selection, then select the next option etc. I added an initial wait for each mouseclick, because otherwise the button was clicked too quickly.
The problem is that after the first selection (first action) and mouseclick (second action) the batch does not continue on to the second selection (third action) and mouseclick (fourth action), instead it begins the batch at the first action again, so it will not finish the batch. I think it picks up the mouseclick as a refresh of the page and therefore restarts the batch, so how do I make sure a batch with multiple mouseclicks gets finished instead of restarted constantly?

![Schermafbeelding 2024-10-28 103047](https://github.com/user-attachments/assets/29b36c86-674f-4b3e-8cdc-d4e980b449e1)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: chrome

**Comment by Hamkaascroissant** [comment]
I'm aware that the first two actions are disabled in the screenshot btw, but the problem happened when all actions were enabled. The actions themselves do work just fine if it's just a pair of selection-mouseclick seperately, but once I add more pairs to the batch, they will just not happen.

**Comment by dharmesh-hemaram** [comment]
does clicking on button change the page content in that case also it takes that as page refresh only. 

If it's something related to answer multiple choice questions . you can combine two options in one .

`//select[@name=""]/option[text()="A" or text()= "B"]`

**Comment by dharmesh-hemaram** [comment]
@Hamkaascroissant let me know if this solved your query . Please open issue again if still facing issue
